Repository streetsidesoftware/vscode-spell-checker, pull requests merged in 2022-06, with the labels that each got.

#1993 fix: Add a workaround for issue with Markdown Rename
  cspell-words.txt
  docs/_includes/generated-docs/configuration.md
  package.json
  packages/_server/spell-checker-config.schema.json
  packages/_server/src/config/cspellConfig.ts
  packages/_server/src/server.ts
  packages/client/src/commands.ts
  packages/client/src/settings/configFields.ts
Labels: documentation, fix

#1995 fix: Upgrade `vscode-language(client/server)` to `v8.0.1`
  packages/_server/package.json
  packages/_serverPatternMatcher/package.json
  packages/client/package.json
  packages/client/src/__mocks__/vscode-languageclient/node.js
  packages/client/src/client/Resolvable.test.ts
  packages/client/src/client/Resolvable.ts
  packages/client/src/client/client.ts
  packages/client/src/client/server/server.ts
  packages/client/src/extension.ts
  packages/client/src/extensionRegEx/patternMatcherClient.ts
  packages/client/src/extensionRegEx/server/server.ts
  packages/client/src/vscode-languageclient.test.ts
  packages/jest-mock-vscode/src/vscode/TypeHierarchyItem.test.ts
  packages/jest-mock-vscode/src/vscode/TypeHierarchyItem.ts
  packages/jest-mock-vscode/src/vscode/index.ts
  yarn.lock
Labels: fix

#2000 fix: Add Sponsor link
  package.json
Labels: fix

#2008 fix: Update VS Code types to 1.68.0
  packages/_integrationTests/package.json
  packages/_server/package.json
  packages/client/package.json
  packages/jest-mock-vscode-examples/package.json
  packages/jest-mock-vscode/package.json
  packages/jest-mock-vscode/src/vscode/languages.ts
  packages/jest-mock-vscode/src/vscode/window.ts
  yarn.lock
Labels: fix

#2007 doc: README - Add "locale" in-document setting
  README.md
Labels: documentation

#2009 ci: Update node version to match VS Code
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  azure-pipelines.yml
Labels: chore

#2015 fix: Fix the needed VS Code version
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  azure-pipelines.yml
  package.json
Labels: fix

#2043 doc: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, chore
